### ISSUE TITLE
Some components are not detected

### ISSUE THREAD

**Issue by anddrzejb** [jsakamoto/FindRazorSourceFile#3]
Hi

I tested this on VS 2019 Preview and VS 2022 Preview (latest). As I stated in the title - some components seem to be invisible. The only difference between the components - the not detected components are using components from external library (in this case [`AntBlazor`](https://antblazor.com)). So if the component is only a wrapper for library component - it is not detected. If the components aside using library components, has its own html & razor - `FindRazorSourceFile` will see the part with html & razor and ignore the parts coming from the library.

Demo:
![findrazorcomponent](https://user-images.githubusercontent.com/6518006/133424682-f61c4f31-fef9-4580-a26e-81598c52eb8e.gif)

Repro:
https://github.com/Hona/BlastOffWithBlazor.Demos
This is a demo solution that @Hona used for his [talk](https://youtu.be/6TIRLsKUqTo?t=1991). The project I used for the gif: `TreeViewComparison` - is already set up with `FindRazorSourceFile` (orignialy I was hoping to include this lib in the talk and @Hona seemed enthusiastic about it as well, but unfortunately I think this bug killed the opportunity). 

Tried this on Firefox 92.0 & Chrome 93.0.4577.82. Same behavior.

**Comment by jsakamoto** [comment]
Hi @anddrzejb !
Thank you for letting me know.

> ...  and ignore the parts coming from the library.
>  (... but unfortunately I think this bug killed the opportunity)

Yes, you are right, but unfortunately, this is the limitation of this tool.

The "Find Razor Source File" is built on a very simple technic, and it depends on the CSS isolation feature built on ASP.NET 5 or later.
This means this tool can detect only elements that were applied with a CSS scope attribute.

This is the reason why the tool couldn't detect the parts coming from the other component libraries.
I have no idea how I can break through this limitation at this time.

Anyway, if you have to detect each of your own .razor files, 

```html
<!-- "AntBlazorTreeView.razor" -->
...
<BadgeRibbon Text="AntBlazor" Placement="start">
  ...
</BadgeRibbon>
<Tree DefaultExpandAll Draggable Multiple Checkable
.  ..>
</Tree>
...
```

please surround the entire component contents with an HTML element. 

```html
<!-- "AntBlazorTreeView.razor" -->
...
<div><!-- 👈 This div element will be applied with a CSS scope attribute. -->
  <BadgeRibbon Text="AntBlazor" Placement="start">
    ...
  </BadgeRibbon>
  <Tree DefaultExpandAll Draggable Multiple Checkable
.    ..>
  </Tree>
</div>
```

I know the workaround above is not good, but I'm sorry I have no more good ideas.

By the way, The ASP.NET team said they would add Blazor support to the "Web Live Preview". 

https://twitter.com/sayedihashimi/status/1415378630700589058

So I will wait for that as the perfect solution.

This tool is just a workaround until the "Web Live Preview" supports Blazor.

**Comment by anddrzejb** [comment]
I will wait then as well. Thank you for your time!
